name: clean-build
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: clean
        run: ./gradlew clean
      - name: build
        run: ./gradlew build