name: clean-build
on: push
runs-on: ubuntu-18.04
jobs:
  build:
    steps:
      - uses: actions/checkout@v1
      - name: clean
        run: ./gradlew clean
      - name: build
        run: ./gradlew build